# Generated by Django 5.1.6 on 2025-02-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemovie',
            name='poster_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='favoritemovie',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoritemovie',
            name='release_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='favoritemovie',
            name='title',
            field=models.CharField(default='Unknown Movie', max_length=255),
            preserve_default=False,
        ),
    ]
