# Generated by Django 5.1.6 on 2025-02-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favoritemovie_poster_path_favoritemovie_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemovie',
            name='title',
            field=models.CharField(default='Unknown Movie', max_length=255),
        ),
    ]
