# Generated by Django 5.1.6 on 2025-03-03 01:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_favoritemovie_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritemovie',
            unique_together={('user', 'movie_id')},
        ),
    ]
