# Generated by Django 5.1.6 on 2025-03-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemovie',
            name='movie_id',
            field=models.CharField(max_length=100),
        ),
    ]
