# Generated by Django 5.1.6 on 2025-04-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_favoritemovie_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemovie',
            name='movie_id',
            field=models.IntegerField(),
        ),
    ]
