# Generated by Django 5.1.6 on 2025-04-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_favoritemovie_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
